# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AmcrViewer
                                 A QGIS plugin
 Viewing and downloading the AMČR data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-03
        copyright            : (C) 2026 by David Spáčil
        email                : spacil@arub.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AmcrViewer class from file AmcrViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .amcr_viewer import AmcrViewer
    return AmcrViewer(iface)
